#METHODS


#  set={1,2,3,"hii"}
# set.add("hello")
#  set.pop()
# set.discard(1)
# set.remove(2)
# print(set)
# set.clear()
# set.copy()


# PROPERTIES OF SETS
# 1) SETS ARE MUTABLE BUT THEIR ELEMENTS ARE IMMUTABLE
# 2) SETS ARE IN UNORDERED WISE
# 3) SETS HAS UNIQUE ELEMENTS COLLECTIONS


# set1={2,43,67,8,56,"patel","yash"}
# set2={32,5,54,34,43,2,"yash"}
# print(set1.union(set2))
# print(set1.intersection(set2))
# print(set1.difference(set2))
# print(set1.symmetric_difference(set2))


# s={1,2,4,6,3,2,4,1,"patel","panchal"}
# print(s)
# print(type(s))
# d={}
# print(type(d))
# s1=set()
# print(type(s1))

# s={1,2,4,6,3,2,4,1,"patel","panchal"}
# s.add(21)
# s.remove(2)
# s.pop()
# print(s)
# s1={2,34,6,67}
# s1.clear()
# print(s1)


s1={1,2,4,6,3,2,4,1,"patel","panchal"}
s2={1,3,65,8,5,2,4,"jallu"}
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
print(s1.symmetric_differencee(s2))
